// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlTZNdA5cVtSCiEo9Fj5Cw19NpeEj8Ms',
    appId: '1:923583430228:web:b01c4dfd6f528ceec437c1',
    messagingSenderId: '923583430228',
    projectId: 'lxservidores-3799d',
    authDomain: 'lxservidores-3799d.firebaseapp.com',
    storageBucket: 'lxservidores-3799d.appspot.com',
    measurementId: 'G-C3DYHFZ4JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPF8-nlTz_nDOy-5X3yDOfFdfbIicqm_A',
    appId: '1:923583430228:android:216ba5bc2e78807cc437c1',
    messagingSenderId: '923583430228',
    projectId: 'lxservidores-3799d',
    storageBucket: 'lxservidores-3799d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxSx_vXfmEUTarRGJIdzKkdba21ysu8E',
    appId: '1:923583430228:ios:a46b7e99d15a70e3c437c1',
    messagingSenderId: '923583430228',
    projectId: 'lxservidores-3799d',
    storageBucket: 'lxservidores-3799d.appspot.com',
    iosBundleId: 'com.example.lxserv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMxSx_vXfmEUTarRGJIdzKkdba21ysu8E',
    appId: '1:923583430228:ios:fcbeaaf60e753a2cc437c1',
    messagingSenderId: '923583430228',
    projectId: 'lxservidores-3799d',
    storageBucket: 'lxservidores-3799d.appspot.com',
    iosBundleId: 'com.example.lxserv.RunnerTests',
  );
}
