// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTHPniXWTzdwmxZCXXpzQNyYSKISdidKE',
    appId: '1:327824562188:web:3f7f5360fe62159ac8f629',
    messagingSenderId: '327824562188',
    projectId: 'lxservidores-teste',
    authDomain: 'lxservidores-teste.firebaseapp.com',
    storageBucket: 'lxservidores-teste.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSvT7LGbkAPMMUuvd1AfkfvPv37vnz44',
    appId: '1:327824562188:android:26e1ed3bad5de4f1c8f629',
    messagingSenderId: '327824562188',
    projectId: 'lxservidores-teste',
    storageBucket: 'lxservidores-teste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6IjwYXuP2pMuhDCdG1o5WRvwqnlv3BDE',
    appId: '1:327824562188:ios:606bf5fd0d8fd19bc8f629',
    messagingSenderId: '327824562188',
    projectId: 'lxservidores-teste',
    storageBucket: 'lxservidores-teste.appspot.com',
    iosBundleId: 'com.example.lxserv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6IjwYXuP2pMuhDCdG1o5WRvwqnlv3BDE',
    appId: '1:327824562188:ios:6f676b942f0ef558c8f629',
    messagingSenderId: '327824562188',
    projectId: 'lxservidores-teste',
    storageBucket: 'lxservidores-teste.appspot.com',
    iosBundleId: 'com.example.lxserv.RunnerTests',
  );
}
